### ISSUE TITLE
Mathematical question about value commitment

### ISSUE THREAD

**Issue by adust09** [anoma/masp#60]
Hi!
Why does cv^{old} apply GroupHash instead of FindGroupHash?
<img width="700" alt="スクリーンショット 2023-08-23 22 25 02" src="https://github.com/anoma/masp/assets/47593288/5bfcfde8-14f3-4fe0-ba77-595ab76cc3b0">

As shown below, FindGroupHash would be appropriate if following Sapling's protocol.
<img width="734" alt="スクリーンショット 2023-08-23 16 03 07" src="https://github.com/anoma/masp/assets/47593288/ae1189e6-3054-4ab7-81f1-9af355b4c70f">
Are FindGroupHash and GroupHash equivalent here?

I would also like to know why [v]FindGroupHash^{J(r)*} -> [v_{old} hJ]vb

**Comment by joebebel** [comment]
Thank you for your question. Yes, the specification should use FindGroupHash instead of GroupHash, as in the original. (The code uses FindGroupHash, so this is an error in the document). The difference is that GroupHash does not always succeed, and FindGroupHash repeatedly calls GroupHash (appending an integer counter) and returns the first time GroupHash succeeds (rejection sampling).

For the value base, this is an important change. The value base is no longer a fixed curve point (found by FindGroupHash) but is a dynamically computed value `vb`. This value base is computed using a PRF in a similar (but not identical) way to GroupHash, and not using FindGroupHash. The main difference between `GroupHash` and `abst_J(PRF_vcg_MASP(t)` is that `GroupHash` includes `URS`, the result of a random beacon. The value base `vb` could be outside the prime-order subgroup of Jubjub, so it must always be multiplied by `h_J` (the cofactor) to put this curve point into the prime-order subgroup.

**Comment by cwgoes** [comment]
The specification has been updated. Thanks for your review and let us know if you have further questions!

**Comment by adust09** [comment]
Thank you!
